DROP TABLE IF EXISTS clubs; 
DROP TABLE IF EXISTS positions; 
DROP TABLE IF EXISTS player; 

CREATE TABLE clubs(
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(30) NOT NULL
);

CREATE TABLE positions(
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    salary DECIMAL (10,2), 
    position VARCHAR(30) NOT NULL
);

CREATE TABLE player (
    id INTEGER AUTO_INCREMENT PRIMARY KEY, 
    first_name VARCHAR(30) NOT NULL, 
    last_name VARCHAR(30) NOT NULL, 
    club_id INTEGER NOT NULL,
    position_id INTEGER NOT NULL, 
);